title: Pedro J. Márquez
email: your-email@example.com
description: >-
  Write an awesome description for your new site here. You can edit this line in
  _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
url: ''
permalink: pretty
plugins:
  - jekyll-feed
sass:
  sass_dir: _sass
collections:
  photo:
    output: true
  cinema:
    output: true
baseurl: ''
