---
new_page_extension: html
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: document
  path: about.html
  label: About Page
- type: directory
  path: _cinema
  label: Cinema Projects
  create: all
  match: "**/*"
  new_doc_ext: html
- type: directory
  path: _photo
  label: Photo Projects
  create: all
  match: "**/*"
  new_doc_ext: html
upload_dir: assets/img
public_path: assets/img
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
